name: Build Chrome Extension and Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies and build
        run: |
          npm ci
          npm install
          npm run build

      - name: Create extension zip
        run: |
          mkdir -p build
          cd dist
          zip -r ../build/extension.zip .

      - name: Create GitHub Release and Upload Extension
        uses: softprops/action-gh-release@v1
        with:
          files: build/extension.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: true
          tag_name: "v${{ github.sha }}"
